id: P496C551A
initial_creation_type: input
source_metadata:
  title: Wealth and Prosperity Series
  language: nl
  description: 'A selection of texts on the theme of wealth and prosperity including
    rites for summoning the spirit of prosperity or abundance (g.yang ''gugs):'
  volume:
    11fea2b8d9f044e8853a1ac0369f4650:
      title: Sang Offering to Yellow Jambhala
      parent: Offering
    e80b0095ea7f4fff8a1718e82c1a1b70:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Offering
    755cb77f7ba344f0a6fe0dca73d1aca4:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Summoning Prosperity
    fceca9bf9e624dbd9af875f9c3c1e0fd:
      title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
      parent: Summoning Prosperity
    433d668b4a37436cb7fab4275a3e8017:
      title: Summoning Prosperity
      parent: Summoning Prosperity
    7576f5f61e4a41f09ca9d6de75383cde:
      title: A Brief Prayer for Summoning Prosperity
      parent: Summoning Prosperity
    54a8e1c00d9449fd9ca0033b02c6532e:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Summoning Prosperity
    f36c66d0e56941adb58eba2934e139ff:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T06:34:53.426780'
last_modified_at: '2022-03-01T06:34:53.426783'
